name: Vnaddons
version: '${project.version}'
main: fr.ft.vnaddons.VNAddons
api-version: 1.19
authors: [ Victor, Noa ]
description: Simple spigot plugin
commands:
  spectate:
    description: Spectate/stop spectating someone
    aliases:
      - spec
  ping:
    description: Get yours or someone's ping
  sendmycoords:
    description: Send your coordinates to the chat
    aliases:
      - smc
